[package]
name = "epoxy_streams"
version = "0.3.0"
authors = ["keatonbrandt <keaton.brandt@gmail.com>"]
edition = "2018"

description = "Base streams implementation for the `epoxy` library. Please use epoxy instead."