[package]
name = "epoxy_streams"
version = "0.3.1"
authors = ["keatonbrandt <keaton.brandt@gmail.com>"]
edition = "2018"
license = "MIT"

description = "Base streams implementation for the `epoxy_frp` library. Please use epoxy_frp instead."